# Example pubspec.yaml for external apps using kimapp packages
# Copy this configuration and adjust the paths/versions as needed

name: example_flutter_app
description: An example Flutter app demonstrating kimapp packages usage

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter dependencies
  cupertino_icons: ^1.0.8
  
  # Kimapp packages - Production setup with Git dependencies
  kimapp:
    git:
      url: https://github.com/yourusername/kimapp_packages.git
      path: packages/kimapp
      ref: kimapp-v0.0.3
  
  kimapp_supabase_helper:
    git:
      url: https://github.com/yourusername/kimapp_packages.git
      path: packages/kimapp_supabase_helper
      ref: kimapp_supabase_helper-v0.0.3
  
  kimapp_generator:
    git:
      url: https://github.com/yourusername/kimapp_packages.git
      path: packages/kimapp_generator
      ref: kimapp_generator-v0.0.2
  
  kimapp_utils:
    git:
      url: https://github.com/yourusername/kimapp_packages.git
      path: packages/kimapp_utils
      ref: kimapp_utils-v0.0.3
  
  # Required dependencies for kimapp packages
  supabase_flutter: ^2.0.0
  riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  logger: ^2.0.0
  fpdart: ^1.1.0
  dartx: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Development dependencies for kimapp_generator
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.0

# For local development, uncomment and use these overrides instead of Git dependencies
# dependency_overrides:
#   kimapp:
#     path: ../kimapp_packages/packages/kimapp
#   kimapp_supabase_helper:
#     path: ../kimapp_packages/packages/kimapp_supabase_helper
#   kimapp_generator:
#     path: ../kimapp_packages/packages/kimapp_generator
#   kimapp_utils:
#     path: ../kimapp_packages/packages/kimapp_utils

flutter:
  uses-material-design: true

# Optional: If you need to run code generation
# scripts:
#   build: flutter pub run build_runner build --delete-conflicting-outputs
#   watch: flutter pub run build_runner watch --delete-conflicting-outputs