name: kimapp_packages
repository: https://github.com/pckimlong/kimapp
environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  # Unpublished packages
  - packages/kimapp
  - packages/kimapp_generator
  - packages/kimapp_utils
  - packages/kimapp_supabase_helper

  # Published packages
  - pubs/autoverpod
  - pubs/autoverpod_generator

  # Examples
  - pubs/autoverpod_generator/example
  - packages/kimapp_generator/example

dev_dependencies:
  melos: ^7.0.0-dev.7
  build_runner: ^2.4.15

melos:
  command:
    version:
      # Only allow versioning to happen on main branch.
      branch: master
      # Generates a link to a prefilled GitHub release creation page.
      releaseUrl: true
      includeCommitId: true
      linkToCommits: true

    bootstrap:
      environment:
        sdk: ">=3.6.0 <4.0.0"
        flutter: ">=3.27.1"

  scripts:
    lint:all:
      steps:
        - analyze
        - format
      description: Run all static analysis checks.
      
    upgrade: melos exec flutter pub upgrade

    analyze:
      run: melos exec dart analyze .
      description: Run `dart analyze` for all packages.

    format-check:
      run: melos exec dart format . --set-exit-if-changed
      description: Run `dart format` checks for all packages.

    update_deps:
      run: melos exec -- flutter pub get
      description: Update dependencies in all packages

    format:
      run: melos exec -- dart format .
      description: Format Dart code in all packages
    
    build_all:
      run: melos exec --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
      description: Run build_runner in all packages that depend on it
      
    publish_dry:
      run: melos exec -- flutter pub publish --dry-run
      description: Run a dry-run of publishing all packages
      
    publish:
      run: melos exec -- flutter pub publish
      description: Publish all packages to pub.dev
      
    test:
      run: melos exec -- flutter test
      description: Run tests in all packages
      
    clean:
      run: melos exec -- flutter clean
      description: Clean all packages
      
    bootstrap:
      run: melos bootstrap
      description: Bootstrap the project by getting all dependencies