targets:
  $default:
    builders:
      kimapp_generator|kimapp_model_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_model.dart
      kimapp_generator|kimapp_form_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_provider.dart
      kimapp_generator|kimapp_table_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_objects.dart
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**_model.dart
            - lib/**_param.dart
      freezed|freezed:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
      auto_route_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/presentation/modules/**.dart
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/**_provider.dart
            - lib/**_repo.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - non_constant_identifier_names
            - require_trailing_commas
            - type=lint