targets:
  $default:
    builders:
      kimapp_generator|kimapp_model_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_model.dart
            - lib/**.schema.dart
          exclude:
            - lib/**.*.*.dart
            - lib/src/presentation/widgets/**.dart
      kimapp_generator|kimapp_form_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_provider.dart
          exclude:
            - lib/**.*.dart
            - lib/src/presentation/widgets/**.dart
      kimapp_generator|kimapp_table_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_objects.dart
            - lib/src/features/**_model.dart
      kimapp_generator|kimapp_schema_builder_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/**_schema.dart
          exclude:
            - lib/**.*.*.dart
            - lib/src/presentation/widgets/**.dart
      autoverpod_generator|autoverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_provider.dart
          exclude:
            - lib/**.*.dart
            - lib/src/presentation/widgets/**.dart
      autoverpod_generator|form_provider_generator:
        enabled: true
        generate_for:
          include:
            - lib/src/features/**_provider.dart
          exclude:
            - lib/**.*.dart
            - lib/src/presentation/widgets/**.dart
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/**_model.dart
            - lib/**_models.dart
            - lib/**_param.dart
            - lib/**.schema.dart
            - lib/**/current_account_provider.dart
            - lib/src/features/org/settings/**.dart
          exclude:
            - lib/**.*.*.dart
            - lib/src/presentation/widgets/**.dart
      freezed|freezed:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
          exclude:
            - lib/**.*.*.dart
            - lib/src/presentation/widgets/**.dart
      auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          include:
            - lib/src/presentation/modules/**_page.dart
          exclude:
            - lib/**.*.dart
            - lib/src/presentation/widgets/**.dart
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          include:
            - lib/src/presentation/router/app_router.dart
          exclude:
            - lib/**.*.dart
            - lib/src/presentation/widgets/**.dart
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/**_provider.dart
            - lib/**_repo.dart
          exclude:
            - lib/**.*.dart
            - lib/src/presentation/widgets/**.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - non_constant_identifier_names
            - require_trailing_commas
            - type=lint