name: {{project_name.snakeCase()}}
description: A project develop by Poch Kimlong

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  easy_localization: ^3.0.2
  animate_do: ^3.0.2
  auto_route: ^7.8.2
  bot_toast: ^4.0.4
  cupertino_icons: ^1.0.5
  dartx: ^1.2.0
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_login: ^4.2.0
  form_builder_validators: ^9.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.8
  intl: null
  json_annotation: ^4.8.1
  kimapp:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp
  kimapp_supabase_helper:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_supabase_helper
  logger: ^2.0.1
  mocktail: ^1.0.0
  package_info_plus: ^4.1.0
  responsive_framework: ^1.1.0
  riverpod_annotation: ^2.1.2
  supabase_flutter: ^1.10.14
  timeago: null
  device_info_plus: ^9.0.3
  path_provider: ^2.1.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  kimapp_generator:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_generator
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/