name: {{project_name.snakeCase()}}
description: A project develop by Poch Kimlong

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  easy_localization: ^3.0.3
  animate_do: ^3.1.2
  auto_route: ^7.8.4
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.6
  dartx: ^1.2.0
  fast_immutable_collections: ^9.1.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_login: ^4.2.1
  form_builder_validators: ^9.1.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.4
  connectivity_plus: ^5.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kimapp:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp
  kimapp_supabase_helper:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_supabase_helper
  logger: ^2.0.2+1
  mocktail: ^1.0.1
  package_info_plus: ^4.2.0
  responsive_framework: ^1.1.1
  riverpod_annotation: ^2.2.1
  supabase_flutter: ^1.10.23
  timeago: ^3.5.0
  device_info_plus: ^9.1.0
  path_provider: ^2.1.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.5
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  flutter_secure_storage: ^9.0.0
  json_serializable: ^6.7.1
  kimapp_generator:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_generator
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/