name: {{project_name.snakeCase()}}
description: A project develop by Poch Kimlong

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  easy_localization: ^3.0.2
  animate_do: null
  auto_route: ^7.1.0
  bot_toast: ^4.0.3
  cupertino_icons: ^1.0.2
  dartx: ^1.1.0
  fast_immutable_collections: ^9.1.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_login: ^4.1.1
  form_builder_validators: ^9.0.0
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.6
  intl: null
  json_annotation: ^4.8.1
  kimapp:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp
  kimapp_supabase_helper:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_supabase_helper
  logger: ^1.3.0
  mocktail: ^0.3.0
  package_info_plus: ^4.0.0
  responsive_framework: ^1.0.0
  riverpod_annotation: ^2.1.1
  supabase_flutter: ^1.9.2
  timeago: null
  device_info_plus: ^9.0.0
  path_provider: ^2.0.15

dev_dependencies:
  auto_route_generator: ^7.0.0
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  kimapp_generator:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_generator
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/translations/