name: {{project_name.snakeCase()}}
description: A project develop by Poch Kimlong

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  talker_riverpod_logger: ^4.6.10
  talker_flutter: ^4.6.10
  easy_localization: ^3.0.7
  animate_do: ^3.3.4
  auto_route: ^9.2.2
  bot_toast: ^4.1.3
  cupertino_icons: ^1.0.8
  dartx: ^1.2.0
  page_transition: ^2.1.0
  fast_immutable_collections: ^11.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_login: ^5.0.0
  form_builder_validators: ^11.1.1
  assorted_layout_widgets: ^10.0.4
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  hive_ce: ^2.8.0
  hive_ce_flutter: ^2.1.0
  hooks_riverpod: ^2.6.1
  connectivity_plus: ^6.1.1
  intl: ^0.20.1
  json_annotation: ^4.9.0
  mocktail: ^1.0.4
  package_info_plus: ^8.1.2
  responsive_framework: ^1.5.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.8.2
  sentry_flutter: ^8.11.2
  timeago: ^3.7.0
  device_info_plus: ^11.2.0
  flex_color_scheme: ^8.1.0
  path_provider: ^2.1.5
  kimapp:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp
  kimapp_supabase_helper:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_supabase_helper
  kimapp_utils:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_utils

dev_dependencies:
  kimapp_generator:
    git:
      url: https://github.com/pckimlong/kimapp.git
      ref: master
      path: packages/kimapp_generator
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.2
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/