# TODO - Change app's name and description
name: kimapp
description: A new Flutter project.


publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  animate_do: ^3.0.2
  auto_route: ^6.0.0-rc-3
  bot_toast: ^4.0.3
  cupertino_icons: ^1.0.2
  dartx: ^1.1.0
  fast_immutable_collections: ^9.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  form_builder_validators: ^8.5.0
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.0
  json_annotation: ^4.8.0
  kimapp:
    git: https://github.com/pckimlong/kimapp.git
  responsive_framework: ^0.2.0
  riverpod_annotation: ^2.0.0
  timeago: 
  intl:

dev_dependencies:
  auto_route_generator: ^6.0.0-rc
  build_runner: ^2.3.3
  custom_lint: ^0.2.12
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  kimapp_generator:
    git: https://github.com/pckimlong/kimapp_generator.git
  riverpod_generator: ^2.0.0
  riverpod_lint: ^1.1.2

flutter:
  uses-material-design: true

assets:
    - assets/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
