// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'package:example/other_schema.schema.dart';
import 'demo_schema.dart';

part 'demo_schema.schema.freezed.dart';
part 'demo_schema.schema.g.dart';

/// Defines the table structure for Demo.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class DemoTable {
  const DemoTable._();

  /// The name of the database table for Demo entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "demos";

  /// Column: id
  /// This is the primary key column for the Demo table.
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: name
  /// Data type: `String?`
  /// Key: `name`
  static const String name = "name";

  /// Column: description
  /// Data type: `String?`
  /// Key: `description`
  static const String description = "description";

  /// Column: age
  /// Data type: `int`
  /// Key: `age`
  static const String age = "age";

  /// Column: address
  /// Data type: `String?`
  /// Key: `address`
  static const String address = "address";

  /// Column: other_id
  /// This is a join key for field other.
  /// Data type: `OtherModel?`
  /// Key: `other`
  static const String other = "other";
}

/// Represents the unique identifier for a Demo.
/// This class wraps the `int` value, providing type safety and encapsulation.
class DemoId extends Identity<int> {
  const DemoId._(this.value);

  @override
  final int value;

  /// Creates an instance of DemoId from a JSON value.
  /// Accepts int representations.
  /// Throws ArgumentError if the value is null or not of type int.
  factory DemoId.fromJson(dynamic value) {
    if (value is int) {
      return DemoId._(value);
    } else if (value == null) {
      throw ArgumentError.notNull('value');
    } else {
      throw ArgumentError(
          'Value of DemoId must be of type int, but was ${value.runtimeType}. Please provide the correct type.');
    }
  }

  /// Creates an instance of DemoId from a int value.
  factory DemoId.fromValue(int value) {
    return DemoId._(value);
  }
}

/// Base model class for DemoModel.
@freezed
class DemoModel with _$DemoModel {
  const DemoModel._();

  /// Table name: `demos`
  static const String tableName = "demos";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for name field with JsonKey('name')
  static const String nameKey = "name";

  /// Field name for description field with JsonKey('description')
  static const String descriptionKey = "description";

  /// Field name for age field with JsonKey('age')
  static const String ageKey = "age";

  /// Field name for address field with JsonKey('address')
  static const String addressKey = "address";

  /// Field name for other field with JsonKey('other')
  /// This is json key for joined field. with foreign key: other_id and candidate key: null
  static const String otherKey = "other";

  /// Constructor for DemoModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`demos`)
  ///
  /// Fields:
  /// - DemoId id : JsonKey('id')
  /// - String? name : JsonKey('name')
  /// - String? description : JsonKey('description')
  /// - int age : JsonKey('age')
  /// - String? address : JsonKey('address')
  /// - OtherModel? other : JsonKey('other')
  @TableModel(DemoModel.tableName)
  const factory DemoModel({
    @JsonKey(name: DemoModel.idKey) required DemoId id,
    @JsonKey(name: DemoModel.nameKey) String? name,
    @JsonKey(name: DemoModel.descriptionKey) String? description,
    @JsonKey(name: DemoModel.ageKey) required int age,
    @JsonKey(name: DemoModel.addressKey) String? address,
    @JoinedColumn(foreignKey: "other_id", candidateKey: null)
    @JsonKey(name: DemoModel.otherKey)
    OtherModel? other,
  }) = _DemoModel;

  /// Creates an instance of DemoModel from a JSON map.
  factory DemoModel.fromJson(Map<String, dynamic> json) =>
      _$DemoModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableDemoModel;
}

/// Represents the DemoDetailModel model. generated by kimapp_generator
@freezed
class DemoDetailModel with _$DemoDetailModel {
  const DemoDetailModel._();

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Constructor for DemoDetailModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `disabled`
  ///
  /// Fields:
  /// - DemoId id : JsonKey('id')
  const factory DemoDetailModel({
    @JsonKey(name: DemoDetailModel.idKey) required DemoId id,
  }) = _DemoDetailModel;

  /// Creates an instance of DemoDetailModel from a JSON map.
  factory DemoDetailModel.fromJson(Map<String, dynamic> json) =>
      _$DemoDetailModelFromJson(json);
}

/// Represents the DemoLiteModel model. generated by kimapp_generator
@freezed
class DemoLiteModel with _$DemoLiteModel {
  const DemoLiteModel._();

  /// Table name: `test`
  static const String tableName = "test";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for description field with JsonKey('description')
  static const String descriptionKey = "description";

  /// Constructor for DemoLiteModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled`
  /// Table Name: `test`
  ///
  /// Fields:
  /// - DemoId id : JsonKey('id')
  /// - String? description : JsonKey('description')
  @TableModel(DemoLiteModel.tableName)
  const factory DemoLiteModel({
    @JsonKey(name: DemoLiteModel.idKey) required DemoId id,
    @JsonKey(name: DemoLiteModel.descriptionKey) required String? description,
  }) = _DemoLiteModel;

  /// Creates an instance of DemoLiteModel from a JSON map.
  factory DemoLiteModel.fromJson(Map<String, dynamic> json) =>
      _$DemoLiteModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableDemoLiteModel;
}
