// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// KimappSchemaGenerator
// **************************************************************************

// ignore_for_file: invalid_annotation_target, unused_import
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:kimapp/kimapp.dart';

import 'new_schema.dart';

part 'new_schema.schema.freezed.dart';
part 'new_schema.schema.g.dart';

/// Defines the table structure for User.
/// This class provides constant string values for table and column names,
/// facilitating type-safe database operations and query building.
class UserTable {
  const UserTable._();

  /// The name of the database table for User entities.
  /// Use this constant for constructing SQL queries to ensure consistency.
  static const String table = "users";

  /// Column: id
  /// This is the primary key column for the User table.
  /// Data type: `int`
  /// Key: `id`
  static const String id = "id";

  /// Column: name
  /// Data type: `String`
  /// Key: `name`
  static const String name = "name";

  /// Column: description
  /// Data type: `String`
  /// Key: `description`
  static const String description = "description";

  /// Column: ignore
  /// This column is ignored for base class generator.
  /// Key: `null`
  static const String ignore = "ignore";

  /// List of all column names for User table.
  static const List<String> allColumns = [
    id,
    name,
    description,
    ignore,
  ];

  /// List of primary key column names for User table.
  static const List<String> primaryKeys = [
    id,
  ];
}

/// Represents the unique identifier for a User.
/// This class wraps the `int` value, providing type safety and encapsulation.
class DemoId extends Identity<int> {
  const DemoId._(this.value);

  @override
  final int value;

  /// Creates an instance of DemoId from a JSON value.
  /// Accepts int representations.
  /// Throws ArgumentError if the value is null or not of type int.
  factory DemoId.fromJson(dynamic value) {
    if (value is int) {
      return DemoId._(value);
    } else if (value == null) {
      throw ArgumentError.notNull('value');
    } else {
      throw ArgumentError(
          'Value of DemoId must be of type int, but was ${value.runtimeType}. Please provide the correct type.');
    }
  }

  /// Creates an instance of DemoId from a int value.
  factory DemoId.fromValue(int value) {
    return DemoId._(value);
  }
}

/// Base model class for UserBaseModel.
@freezed
class UserBaseModel with _$UserBaseModel {
  const UserBaseModel._();

  /// Table name: `users`
  static const String tableName = "users";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for name field with JsonKey('name')
  static const String nameKey = "name";

  /// Field name for description field with JsonKey('description')
  static const String descriptionKey = "description";

  /// Constructor for UserBaseModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled` (`users`)
  ///
  /// Fields:
  /// - DemoId id : JsonKey('id')
  /// - String name : JsonKey('name')
  /// - String description : JsonKey('description')
  @TableModel(UserBaseModel.tableName)
  const factory UserBaseModel({
    @JsonKey(name: UserBaseModel.idKey) required DemoId id,
    @JsonKey(name: UserBaseModel.nameKey) required String name,
    @JsonKey(name: UserBaseModel.descriptionKey) required String description,
  }) = _UserBaseModel;

  /// Creates an instance of UserBaseModel from a JSON map.
  factory UserBaseModel.fromJson(Map<String, dynamic> json) =>
      _$UserBaseModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableUserBaseModel;
}

/// Represents the UserDetailModel model. generated by kimapp_generator
@freezed
class UserDetailModel with _$UserDetailModel {
  const UserDetailModel._();

  /// Table name: `v_user_detail`
  static const String tableName = "v_user_detail";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for name field with JsonKey('name')
  static const String nameKey = "name";

  /// Field name for description field with JsonKey('description')
  static const String descriptionKey = "description";

  /// Constructor for UserDetailModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled`
  /// Table Name: `v_user_detail`
  ///
  /// Fields:
  /// - DemoId id : JsonKey('id')
  /// - String name : JsonKey('name')
  /// - String description : JsonKey('description')
  @TableModel(UserDetailModel.tableName)
  const factory UserDetailModel({
    @JsonKey(name: UserDetailModel.idKey) required DemoId id,
    @JsonKey(name: UserDetailModel.nameKey) required String name,
    @JsonKey(name: UserDetailModel.descriptionKey) required String description,
  }) = _UserDetailModel;

  /// Creates an instance of UserDetailModel from a JSON map.
  factory UserDetailModel.fromJson(Map<String, dynamic> json) =>
      _$UserDetailModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableUserDetailModel;
}

/// Represents the UserLiteModel model. generated by kimapp_generator
@freezed
class UserLiteModel with _$UserLiteModel {
  const UserLiteModel._();

  /// Table name: `test`
  static const String tableName = "test";

  /// Field name for id field with JsonKey('id')
  static const String idKey = "id";

  /// Field name for name field with JsonKey('name')
  static const String nameKey = "name";

  /// Field name for description field with JsonKey('description')
  static const String descriptionKey = "description";

  /// Constructor for UserLiteModel.
  ///
  /// This class was generated by the Kimapp generator based on KimappSchema.
  ///
  /// Table Mode: `enabled`
  /// Table Name: `test`
  ///
  /// Fields:
  /// - DemoId id : JsonKey('id')
  /// - String name : JsonKey('name')
  /// - String description : JsonKey('description')
  @TableModel(UserLiteModel.tableName)
  const factory UserLiteModel({
    @JsonKey(name: UserLiteModel.idKey) required DemoId id,
    @JsonKey(name: UserLiteModel.nameKey) required String name,
    @JsonKey(name: UserLiteModel.descriptionKey) required String description,
  }) = _UserLiteModel;

  /// Creates an instance of UserLiteModel from a JSON map.
  factory UserLiteModel.fromJson(Map<String, dynamic> json) =>
      _$UserLiteModelFromJson(json);

  /// Supabase table configuration for this model.
  static const TableBuilder table = _tableUserLiteModel;
}
