name: autoverpod_generator
description: Code generator for autoverpod annotations to create Riverpod widgets
version: 0.0.2
repository: https://github.com/pckimlong/kimapp

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  source_gen: ^2.0.0
  recase: ^4.1.0
  build: ^2.4.2
  meta: ^1.16.0
  analyzer: ^7.3.0 
  riverpod_annotation: ^2.3.4
  dart_style: ^3.0.1
  collection: ^1.19.1
  riverpod: ^2.6.1
  code_builder: ^4.10.1
  autoverpod:
    path: ./pubs/autoverpod
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.4.7
