builders:
  kimapp_table_generator:
    import: "package:kimapp_generator/builder.dart"
    builder_factories: ["kimappTableGenerator"]
    build_extensions: {".dart": [".table.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before:
      - freezed|freezed
      - kimapp_generator|kimapp_model_generator
      - kimapp_generator|kimapp_form_generator
      - json_serializable|json_serializable
      - riverpod_generator|riverpod_generator
      - auto_route_generator|auto_route_generator

  kimapp_state_widget_generator:
    import: "package:kimapp_generator/builder.dart"
    builder_factories: ["kimappStateWidgetGenerator"]
    build_extensions: {".dart": [".widget.dart"]}
    required_inputs: [".freezed.dart", ".g.dart"]
    auto_apply: dependents
    build_to: source
  
  kimapp_schema_builder_generator:
    import: "package:kimapp_generator/builder.dart"
    builder_factories: ["kimappSchemaBuilderGenerator"]
    build_extensions: {".dart": [".schema.dart"]}
    auto_apply: dependents
    build_to: source
    runs_before:
      - freezed|freezed
      - kimapp_generator|kimapp_model_generator
      - kimapp_generator|kimapp_form_generator
      - json_serializable|json_serializable
      - riverpod_generator|riverpod_generator
      - auto_route_generator|auto_route_generator

  kimapp_model_generator:
    import: "package:kimapp_generator/builder.dart"
    builder_factories: ["kimappModelGenerator"]
    build_extensions: {".dart": ["kimapp_model_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    required_inputs: [".freezed.dart"]
    applies_builders: ["source_gen|combining_builder"]

  kimapp_form_generator:
    import: "package:kimapp_generator/builder.dart"
    builder_factories: ["kimappFormGenerator"]
    build_extensions: {".dart": ["kimapp_form_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

