builders:
  riverpod_widget_generator:
    import: "package:riverpod_widget/builder.dart"
    builder_factories: ["riverpodWidgetGenerator"]
    build_extensions: {".dart": [".widget.dart"]}
    auto_apply: dependents
    build_to: source
    required_inputs:
      - ".freezed.dart"
      - ".g.dart"
    applies_builders: ["source_gen|combining_builder"]

  form_provider_generator:
    import: "package:riverpod_widget/builder.dart"
    builder_factories: ["formProviderBuilder"]
    build_extensions: {".dart": [".form.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    required_inputs:
      - ".freezed.dart"