name: riverpod_widget
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0


dependencies:
  source_gen: ^2.0.0
  test: 
  recase: ^4.1.0
  build: ^2.4.2
  meta:
  analyzer: 
  riverpod_annotation: ^2.3.4
  dart_style: ^3.0.1
  riverpod:
  code_builder: ^4.10.1
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  build_runner: ^2.4.7
