name: autoverpod_example
description: Example for the autoverpod package
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  autoverpod: ^0.0.4
    path: ../
    path: ./pubs/autoverpod