name: example
description: An example of using model_forge
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  model_forge:
    path: ../

dev_dependencies:
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
