name: numpad_input
description: "A customizable Flutter widget for numeric input, featuring a calculator-style numpad, amount formatting, and easy integration for financial or data entry apps."
version: 0.0.1
repository: https://github.com/pckimlong/kimapp

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  fast_immutable_collections: ^11.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^3.0.0
  intl: ^0.20.2
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
