name: Publish Kimapp Snippets Extension

on:
  push:
    branches: [ main, master ]
    paths:
      - 'tools/extensions/kimapp-snippets/**'
      - 'template_generators/kimapp_feature/**'  # Also trigger when the source code changes

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[publish-snippets]')
    permissions:
      contents: write  # This permission is needed for creating releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install global dependencies
        run: npm install -g @vscode/vsce
          
      - name: Install extension dependencies
        working-directory: ./tools/extensions/kimapp-snippets
        run: npm install
        
      - name: Verify kimapp_feature source exists
        run: |
          if [ ! -d "./template_generators/kimapp_feature" ]; then
            echo "Error: kimapp_feature source directory not found!"
            exit 1
          fi
          
      - name: Copy kimapp_feature to extension
        working-directory: ./tools/extensions/kimapp-snippets
        run: node ./copy-kimapp-feature.js
        
      - name: Run tests
        working-directory: ./tools/extensions/kimapp-snippets
        run: npm run test
          
      - name: Package extension
        working-directory: ./tools/extensions/kimapp-snippets
        run: npm run package
        
      - name: Verify packaged extension
        working-directory: ./tools/extensions/kimapp-snippets
        run: |
          # Get version from package.json
          VERSION=$(node -p "require('./package.json').version")
          VSIX_FILE="kimapp-snippets-${VERSION}.vsix"
          
          if [ ! -f "$VSIX_FILE" ]; then
            echo "Error: VSIX package not created! Expected file: $VSIX_FILE"
            ls -la
            exit 1
          fi
          echo "Successfully packaged extension: $VSIX_FILE"
          
      - name: Publish to VS Code Marketplace
        working-directory: ./tools/extensions/kimapp-snippets
        run: vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
          
      - name: Get version from package.json
        id: get_version
        working-directory: ./tools/extensions/kimapp-snippets
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: tools/extensions/kimapp-snippets/*.vsix
          name: "Kimapp Snippets v${{ steps.get_version.outputs.VERSION }}"
          tag_name: "snippets-v${{ steps.get_version.outputs.VERSION }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 