name: Release

on:
  push:
    branches:
      - master
    paths:
      - "packages/**"
      - "pubs/**"
      - "pubspec.yaml"
  workflow_dispatch:  # Allow manual triggering
    inputs:
      force_version:
        description: 'Force version (leave empty for automatic)'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub global activate melos
          flutter pub get
          melos bootstrap

      - name: Setup git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Verify packages
        run: melos run verify

      - name: Check for changes
        id: check_changes
        run: |
          CHANGES=$(git diff --name-only HEAD~1 HEAD | grep -E "^(packages|pubs)/" || true)
          if [ -n "$CHANGES" ] || [ -n "${{ github.event.inputs.force_version }}" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Version packages
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          if [ -n "${{ github.event.inputs.force_version }}" ]; then
            melos version --yes --exact "${{ github.event.inputs.force_version }}"
          else
            melos version --yes
          fi
          git push --follow-tags

      - name: Generate changelog
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          melos run changelog
          # Ensure CHANGELOG.md exists
          touch CHANGELOG.md

      - name: Create GitHub Release
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: melos run release 