name: Release

on:
  push:
    branches:
      - master
    paths:
      - "packages/**"
      - "pubs/**"
      - "pubspec.yaml"
  workflow_dispatch:  # Allow manual triggering
    inputs:
      force_version:
        description: 'Force version (leave empty for automatic)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for detecting all changes

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub global activate melos
          flutter pub get
          melos bootstrap

      - name: Setup git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Verify packages
        run: melos run verify

      - name: Check for changes
        id: check_changes
        run: |
          # Get the last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            # If no tags exist, compare with initial commit
            COMPARE_WITH=$(git rev-list --max-parents=0 HEAD)
          else
            COMPARE_WITH=$LAST_TAG
          fi
          
          # Check for changes since last tag/initial commit
          CHANGES=$(git diff --name-only $COMPARE_WITH HEAD | grep -E "^(packages/|pubs/|pubspec\.yaml)" || true)
          
          if [ -n "$CHANGES" ] || [ -n "${{ github.event.inputs.force_version }}" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "changes=$CHANGES" >> $GITHUB_OUTPUT
            echo "Found changes in monitored paths since $COMPARE_WITH"
            echo "$CHANGES"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes found in monitored paths since $COMPARE_WITH"
          fi

      - name: Version packages
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Function to check if there are changes in specific directory
          check_dir_changes() {
            local dir=$1
            echo "$CHANGES" | grep -q "^$dir/"
            return $?
          }
          
          # Get the changes from the previous step
          CHANGES="${{ steps.check_changes.outputs.changes }}"
          
          # Version packages based on changes
          if check_dir_changes "packages" || check_dir_changes "pubs"; then
            if check_dir_changes "packages"; then
              echo "Versioning kimapp packages..."
              melos version --scope="kimapp*" --yes
            fi
            
            if check_dir_changes "pubs"; then
              echo "Versioning autoverpod packages..."
              melos version --scope="autoverpod*" --yes
            fi
            
            # Push changes and tags
            git push --follow-tags
          elif [ -n "${{ github.event.inputs.force_version }}" ]; then
            # Handle manual version override
            melos version --yes --exact "${{ github.event.inputs.force_version }}"
            git push --follow-tags
          fi

      - name: Generate changelog
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          melos run changelog
          # Ensure CHANGELOG.md exists
          touch CHANGELOG.md

      - name: Create GitHub Release
        if: steps.check_changes.outputs.has_changes == 'true'
        run: melos run release 