name: Release

on:
  push:
    branches:
      - master
    paths:
      - "packages/**"
      - "pubs/**"
      - "pubspec.yaml"
  workflow_dispatch:  # Allow manual triggering
    inputs:
      force_version:
        description: 'Force version (leave empty for automatic)'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important for detecting all changes

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub global activate melos
          flutter pub get
          melos bootstrap

      - name: Setup git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Verify packages
        run: melos run verify

      - name: Check for changes
        id: check_changes
        run: |
          # Get the last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            # If no tags exist, compare with initial commit
            COMPARE_WITH=$(git rev-list --max-parents=0 HEAD)
          else
            COMPARE_WITH=$LAST_TAG
          fi
          
          # Check for changes since last tag/initial commit
          CHANGES=$(git diff --name-only $COMPARE_WITH HEAD | grep -E "^(packages/|pubs/|pubspec\.yaml)" || true)
          
          if [ -n "$CHANGES" ] || [ -n "${{ github.event.inputs.force_version }}" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "changes=$CHANGES" >> $GITHUB_OUTPUT
            echo "Found changes in monitored paths since $COMPARE_WITH"
            echo "$CHANGES"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes found in monitored paths since $COMPARE_WITH"
          fi

      - name: Generate changelog
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Create empty CHANGELOG.md
          echo "# Changelog" > CHANGELOG.md
          
          # Generate changelog
          melos run changelog || true
          
          # Ensure the changelog exists and has content
          if [ ! -s CHANGELOG.md ]; then
            echo "No changes to document in this release." >> CHANGELOG.md
          fi

      - name: Create GitHub Release
        if: steps.check_changes.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Get the latest version
          LATEST_VERSION=$(git describe --tags --abbrev=0)
          
          # Run release command
          melos run release || gh release create "${LATEST_VERSION}" \
            --title "Release ${LATEST_VERSION}" \
            --notes-file CHANGELOG.md 